[build]
  # Build command - not needed for static site
  command = ""
  # Publish directory - root of the project
  publish = "."

[build.environment]
  # Environment variables for build process
  NODE_VERSION = "18"

# Form handling configuration
[[forms]]
  # Enable Netlify Forms for contact form
  name = "contact"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache control for static assets
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    # Different cache settings for HTML files
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/assets/*"
  [headers.values]
    # Long cache for assets
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects for clean URLs and SEO
[[redirects]]
  from = "/home"
  to = "/"
  status = 301

[[redirects]]
  from = "/home.html"
  to = "/"
  status = 301

# 404 page
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# Custom domain settings (update when domain is configured)
# [context.production]
#   environment = { NODE_ENV = "production" }

# Performance optimizations
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true